version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vr-iot-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - BROKER_ADDRESS=mosquitto
      - BROKER_PORT=9001
      - USE_WEBSOCKETS=true
    depends_on:
      - mosquitto
    networks:
      - vr-iot-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: vr-iot-mqtt
    restart: always
    ports:
      - "1883:1883"  
      - "9001:9001"  
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - vr-iot-network

networks:
  vr-iot-network:
    driver: bridge