name: .NET Backend CI - Build and Test

on:
  push:
    branches:
      - test-branch   #
  pull_request:
    branches:
      - test-branch  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  

      - name: Restore dependencies
        run: |
          dotnet restore backend.sln  # Restore the .NET project dependencies

      - name: Build project
        run: |
          dotnet build backend.sln --configuration Release  # Build the project in Release mode

      - name: Run tests
        run: |
          dotnet test backend.sln --configuration Release --no-build --collect:"XUnit"  # Run tests

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-results
          path: backend.Tests/TestResults/*.xml  

      - name: Build Docker Image (Optional)
        run: |
          docker build -t dotnet-backend .  # Build the Docker image for the backend
